### PR TITLE
Update to Arithcode v1.2

### PR DESCRIPTION
**Pull request by tfmorris**
Minor code changes with nothing worrying looking. Adds tests and has minor package refactoring.

Code diffs from the v1.1 that we were using can be reviewed here: https://github.com/tfmorris/java-arithcode/compare/master...tfmorris:v1.1

### CODE REVIEW

**Comment by wetneb** [comment]
I will upload this new version to Maven Central for this to work.

**Comment by wetneb** [comment]
(by the way we could also set you up for Maven Central uploads, Tom, let me know if you are interested)

**Comment by wetneb** [comment]
The upload process looks like this, after adapting [the POM file](https://search.maven.org/artifact/org.openrefine.dependencies/arithcode/1.1/jar) to the new version:
```
mvn gpg:sign-and-deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ -DrepositoryId=ossrh -DpomFile=pom.xml -Dfile=arithcode-1.2.jar
mvn gpg:sign-and-deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ -DrepositoryId=ossrh -DpomFile=pom.xml -Dfile=arithcode-1.2-javadoc.jar -Dclassifier=javadoc
mvn gpg:sign-and-deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ -DrepositoryId=ossrh -DpomFile=pom.xml -Dfile=arithcode-1.2-sources.jar -Dclassifier=sources
```

**Comment by tfmorris** [comment]
Thanks!

> (by the way we could also set you up for Maven Central uploads, Tom, let me know if you are interested)

What do you need to set this up? Just my public key?

**Comment by wetneb** [comment]
You need to create a Sonatype JIRA account (https://issues.sonatype.org/secure/Signup!default.jspa) and then let me know your username. The GPG key will only be needed to sign the artifacts you upload, it does not look like we need to register it in the system anywhere else.

**Comment by tfmorris** [comment]
My Sonatype account name is tfmorris. Let me know if you need anything else.

**Comment by wetneb** [comment]
Requested here: https://issues.sonatype.org/browse/OSSRH-59485

**Comment by tfmorris** [comment]
@wetneb It looks like I've got access to the group and arithcode 1.2 has been published, so I'll see if I can get vicino 1.2 published on my own.

**Pull request merged**
